server:
    port: 9090

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: hjj1234

mybatis:
    type-aliases-package: com.example.springboot.bean
    mapper-locations: classpath*:/mapper/*Mapper.xml

#showSql
logging:
    level:
        com:
            example:
                mapper: debug
